filter:
  excluded_paths:
    - "tests/*"
    - "doc/*"
    - "var/*"
  dependency_paths:
    - "vendor/*"

before_commands:
  - "composer install --prefer-source"

build:
  environment:
    php: 7.3.25
  nodes:
    analysis:
      dependencies:
        before:
          - sudo apt-get install -y libyaml-dev
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit
            coverage:
              file: var/phpunit/test-clover.xml
              format: clover

tools:
  external_code_coverage: false
  php_code_sniffer: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_sim: true
  php_changetracking: true

  php_cs_fixer:
    enabled: true
    config:
      level: all
    filter:
      excluded_paths:
        - "tests/*"
        - "doc/*"
        - "vendor/*"
        - "var/*"

  php_mess_detector:
    enabled: true
    filter:
      excluded_paths:
        - "tests/*"
        - "doc/*"
        - "vendor/*"
        - "var/*"

  php_pdepend:
    enabled: true
    filter:
      excluded_paths:
        - "tests/*"
        - "doc/*"
        - "vendor/*"
        - "var/*"

  php_cpd:
    enabled: true
    excluded_dirs:
      - "tests/*"
      - "doc/*"
      - "vendor/*"
      - "var/*"

  php_loc:
    enabled: true
    excluded_dirs:
      - "tests/*"
      - "doc/*"
      - "vendor/*"
      - "var/*"