os: linux
dist: xenial
language: php

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - git config --global user.email test@test.com
  - git config --global user.name "Test User"
  - composer self-update

install:
  - composer install -o --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover