translators:
  - {class: 'ImgFinder\Translate\Translators\DictionaryYaml', params: {filename: img-finder/doc/examples/dictionary.yml}}
  - {class: 'ImgFinder\Translate\Translators\GoogleTranslate', params: {credentials: foo, from: es, to: es }}

repositories:
  - {class: 'ImgFinder\Repository\UnsplashRepository', params: {applicationId: ~}}
  - {class: 'ImgFinder\Repository\PexelsRepository', params: {user: ~, password: ~}}
